column_mapping:
  categorical_features:
  - _the_
  - arctic
  - drastically
  - effort
  - esteem
  - fierce
  - propoganda
  - sponsored
  - thief
  - warrior
  datetime: __date__
  numerical_features: []
  prediction: __predicted__
  target: __target__
data_format:
  date_column: __date__
  header: true
  separator: ','
pretty_print: true
service:
  calculation_period_sec: 10
  min_reference_size: 30
  monitors:
  - data_drift
  - concept_drift
  - regression_performance
  moving_reference: false
  reference_path: data/reference.csv
  use_reference: true
  window_size: 30
