---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
        scrape_interval: 15s
        evaluation_interval: 15s
        external_labels:
            monitor: 'my-project'
    rule_files:
        - /etc/prometheus/prometheus.rules
    alerting:
        alertmanagers:
            - scheme: http
                static_configs:
                    - targets:
                        - "alertmanager:9093"
    scrape_configs:
        - job_name: "prometheus"
            static_configs:
                - targets: ['localhost:9090']
        - job_name: 'drift_monitoring_service'
            static_configs:
                - targets: ['drift_monitoring_service.:5000']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  grafana_datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "name": "Prometheus",
                "type": "prometheus",
                "access":"proxy",
                "url": "http://prometheus.:9090",
                "orgId": 1
            }
        ],
        "deleteDatasources": [
              {
                  "name": "Prometheus",
                  "orgId": 1,
              }
        ]
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    app: grafana
data:
  grafana_dashboards.yaml: |-
    {
        "apiVersion": 1,
        "providers": [
            {
                "name": "Drift Monitoring Dashboards",
                "type": "file",
                "access":"proxy",
                "url": "http://prometheus.:9090",
                "orgId": 1,
                "folder": "",
                "folderUid": "",
                "disableDeletion": "false",
                "updateIntervalSeconds": 10,
                "allowUiUpdates": "false",
                "options": [
                    {
                        "path": "/opt/grafana/dashboards",
                        "foldersFromFilesStructure": "true",
                    }
                ]
            }
        ]
    }
