apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      # no nodePort specified so one will be automatically assigned from the 30000-32000 range
  selector:
    component: grafana
  type: LoadBalancer
status:
  loadBalancer: {}
