# my global config
global:
  scrape_interval: 15s      # Set the scrape interval.  Default is every 1 minute.
  evaluation_interval: 15s  # Set the evaluation interval.  Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every n seconds.
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:9090']

  # Add a new job name to scrape time series from the drift monitoring service, running on port 5000.
  - job_name: 'drift_monitoring_service'
    # Override the global default and scrape targets from this job every n seconds.
    scrape_interval: 3s
    static_configs:
      - targets: ['drift_monitoring_service.:5000']
