column_mapping:
  categorical_features: []
  datetime: date_
  numerical_features:
  - article
  - com
  - god
  - host
  - just
  - people
  - rutgers
  - space
  - think
  - time
  prediction: predicted_
  target: target_
data_format:
  date_column: date_
  header: true
  separator: ','
pretty_print: true
service:
  calculation_period_sec: 10
  min_reference_size: 30
  monitors:
  - data_drift
  - concept_drift
  - regression_performance
  moving_reference: false
  reference_path: ./data/reference_1.csv
  use_reference: true
  window_size: 30
